DoAn/Models/TINTUC.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public int ID { get; set; }
        public string TenTinTuc { get; set; }
        public string MoTa { get; set; }
        public string NoiDung { get; set; }
        public string TuKhoa { get; set; }
        public int DMTT_ID { get; set; }
        public string TieuDeSeo { get; set; }
        public string Alias { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual DMTT DMTT { get; set; }
    }
}

DoAn/Areas/admin/Controllers/TINTUCsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAn.Models;
using System.IO;
using ImageResizer;
using DoAn.App_Start;

namespace DoAn.Areas.admin.Controllers
{
    public class TINTUCsController : Controller
    {
        private WebCayCanhEntities db = new WebCayCanhEntities();
        public string urlImage = "/files/image/" + DateTime.Now.Year + "/" + DateTime.Now.Month + "/" + DateTime.Now.Day + "/";

        public string UploadImage(HttpPostedFileBase hinhanh)
        {
            string pic = Path.GetFileName(hinhanh.FileName);
            string pfull = System.IO.Path.Combine(Server.MapPath(urlImage));
            if (!Directory.Exists(pfull))
                Directory.CreateDirectory(pfull);
            string path = System.IO.Path.Combine(Server.MapPath(urlImage), pic);

            hinhanh.SaveAs(path);
            ResizeSettings resizeSetting = new ResizeSettings
            {
                Width = 320,
                Height = 320,
                Format = "png"
            };
            ImageBuilder.Current.Build(path, path, resizeSetting);
            return urlImage + pic;
        }

        public ActionResult Index()
        {
            var tINTUC = db.TINTUC.Include(t => t.DMTT);
            return View(tINTUC.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TINTUC tINTUC = db.TINTUC.Find(id);
            if (tINTUC == null)
            {
                return HttpNotFound();
            }
            return View(tINTUC);
        }


        public ActionResult Create()
        {
            ViewBag.DMTT_ID = new SelectList(db.DMTT, "ID", "TenDMTT");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TINTUC tINTUC, HttpPostedFileBase hinhanh)
        {
            try
            {
                if (hinhanh != null)
                {
                    tINTUC.HinhAnh = UploadImage(hinhanh);
                }
                else
                {
                    tINTUC.HinhAnh = "https://png.pngtree.com/png-clipart/20190611/original/pngtree-404-hand-painted-pattern-png-image_2805465.jpg";
                }
                tINTUC.Alias = ConfigWeb.convertToUnSign3(tINTUC.TenTinTuc);
                db.TINTUC.Add(tINTUC);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {

            }
            ViewBag.DMTT_ID = new SelectList(db.DMTT, "ID", "TenDMTT", tINTUC.DMTT_ID);
            return View(tINTUC);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TINTUC tINTUC = db.TINTUC.Find(id);
            if (tINTUC == null)
            {
                return HttpNotFound();
            }
            ViewBag.DMTT_ID = new SelectList(db.DMTT, "ID", "TenDMTT", tINTUC.DMTT_ID);
            return View(tINTUC);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TINTUC tINTUC, HttpPostedFileBase hinhanh)
        {
            try
            {
                if (hinhanh != null)
                {
                    tINTUC.HinhAnh = UploadImage(hinhanh);
                }
                 
                tINTUC.Alias = ConfigWeb.convertToUnSign3(tINTUC.TenTinTuc);
                db.Entry(tINTUC).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.DMTT_ID = new SelectList(db.DMTT, "ID", "TenDMTT", tINTUC.DMTT_ID);
                return View(tINTUC);
            }

        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TINTUC tINTUC = db.TINTUC.Find(id);
            if (tINTUC == null)
            {
                return HttpNotFound();
            }
            return View(tINTUC);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TINTUC tINTUC = db.TINTUC.Find(id);
            db.TINTUC.Remove(tINTUC);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAn/Areas/admin/Views/TINTUCs/Create.cshtml
@model DoAn.Models.TINTUC

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}



@using (Html.BeginForm("Create", "TINTUCs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Thêm Mới Tin Tức</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Tên Tin Tức", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTinTuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTinTuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mô Tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nội Dung", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Từ Khóa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TuKhoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TuKhoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Hình Ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              <input type="file" id="hinhanh" name="hinhanh" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DMTT_ID, "DMTT_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DMTT_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DMTT_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tiêu Đề Seo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TieuDeSeo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TieuDeSeo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm Mới" class="btn btn-success" />
                <a class="btn btn-danger" href="/Admin/tintucs">HỦY</a>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở Về", "Index")
</div>

DoAn/Areas/admin/Views/TINTUCs/Delete.cshtml
@model DoAn.Models.TINTUC

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Xóa Tin Tức</h2>

<h3>Bạn Có Muốn Xóa?</h3>
<div>
   
    <hr />
    <div class="row" style="margin-left:10px">
        <div class="col-sm-12">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.TenTinTuc)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TenTinTuc)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.MoTa)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MoTa)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.NoiDung)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NoiDung)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TuKhoa)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TuKhoa)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.HinhAnh)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.HinhAnh)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TieuDeSeo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TieuDeSeo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Alias)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Alias)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DMTT.TenDMTT)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DMTT.TenDMTT)
                </dd>

            </dl>
            </div>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Xóa" class="btn btn-default" /> |
                @Html.ActionLink("Trở Về", "Index")
            </div>
        }
    </div>

DoAn/Areas/admin/Views/TINTUCs/Details.cshtml
@model DoAn.Models.TINTUC

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";

<h2>Details</h2>

<div>
    <h4>TINTUC</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenTinTuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTinTuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoiDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TuKhoa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TuKhoa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TieuDeSeo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TieuDeSeo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DMTT.TenDMTT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DMTT.TenDMTT)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DoAn/Areas/admin/Views/TINTUCs/Edit.cshtml
@model DoAn.Models.TINTUC

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm("Edit", "TINTUCs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chỉnh Sửa Tin Tức</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.HinhAnh)

        <div class="form-group">
            @Html.LabelFor(model => model.TenTinTuc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTinTuc, new { htmlAttributes = new { @class = "form-control" } })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TuKhoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TuKhoa, new { htmlAttributes = new { @class = "form-control" } })
                
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Model.HinhAnh"/>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Thay đổi hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="hinhanh" name="hinhanh" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DMTT_ID, "DMTT_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DMTT_ID", null, htmlAttributes: new { @class = "form-control" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TieuDeSeo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TieuDeSeo, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu Lại" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở Về", "Index")
</div>

DoAn/Areas/admin/Views/TINTUCs/Index.cshtml
@model IEnumerable<DoAn.Models.TINTUC>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="row" style="margin-left:10px">
    <div class="col-sm-12">
        <h2>Tin Tức</h2>
        <p><a class="btn btn-success" style="border-radius:0" href="/admin/tintucs/Create">THÊM MỚI</a></p>
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    Tên Tin Tức
                </th>
                <th>
                    Mô Tả
                </th>
                <th>
                   Nội Dung
                </th>
                <th>
                  Từ Khóa
                </th>
                <th>
                    Tiêu Đề Seo
                </th>
                <th>
                    Alias
                </th>
                <th>
                    Hình Ảnh
                </th>
               
                <th>
                    Tên Danh Mục
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenTinTuc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MoTa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NoiDung)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TuKhoa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TieuDeSeo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Alias)
                    </td>
                    <td>
                        <img src="@item.HinhAnh" width="100" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DMTT.TenDMTT)
                    </td>
                    <td>
                        <a class="btn btn-warning btn-xs" style="border-radius:0" href="/Admin/tintucs/edit/@item.ID"><i class="fa fa-edit"></i></a> |

                        <a class="btn btn-danger btn-xs" style="border-radius:0" href="/Admin/tintucs/delete/@item.ID"><i class="fa fa-recycle"></i></a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>